CREATE TABLE merchant (
    id NUMBER(19, 0) GENERATED BY DEFAULT AS IDENTITY,
    merchant_name VARCHAR2(255),
    merchant_address VARCHAR2(255),
    CONSTRAINT pk_merchant PRIMARY KEY (id)
);

CREATE SEQUENCE merchant_transaction_id_seq
    START WITH 1
    INCREMENT BY 1;

CREATE TABLE merchant_transaction (
    id NUMBER(19, 0) NOT NULL,
    transaction_amount NUMBER(19, 2),
    transaction_date TIMESTAMP,
    merchant_id NUMBER(19, 0) NOT NULL,
    transaction_type VARCHAR2(50),
    transaction_status VARCHAR2(50),
    connection_mode VARCHAR2(20),
    CONSTRAINT pk_merchant_transaction PRIMARY KEY (id),
    CONSTRAINT fk_merchant_transaction_merchant
        FOREIGN KEY (merchant_id)
        REFERENCES merchant (id)
);

CREATE INDEX idx_merchant_transaction_merchant_id
    ON merchant_transaction (merchant_id);

CREATE INDEX idx_merchant_transaction_transaction_date
    ON merchant_transaction (transaction_date);

CREATE INDEX idx_merchant_transaction_merchant_date
    ON merchant_transaction (merchant_id, transaction_date);
