CREATE TABLE merchant (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    merchant_name VARCHAR(255),
    merchant_address VARCHAR(255),
    CONSTRAINT pk_merchant PRIMARY KEY (id)
);

CREATE SEQUENCE merchant_transaction_id_seq
    START WITH 1
    INCREMENT BY 1;

CREATE TABLE merchant_transaction (
    id BIGINT NOT NULL,
    transaction_amount DECIMAL(19, 2),
    transaction_date TIMESTAMP,
    merchant_id BIGINT NOT NULL,
    transaction_type VARCHAR(50),
    transaction_status VARCHAR(50),
    connection_mode VARCHAR(20),
    CONSTRAINT pk_merchant_transaction PRIMARY KEY (id),
    CONSTRAINT fk_merchant_transaction_merchant
        FOREIGN KEY (merchant_id)
        REFERENCES merchant (id)
);

CREATE INDEX idx_merchant_transaction_merchant_id
    ON merchant_transaction (merchant_id);

CREATE INDEX idx_merchant_transaction_transaction_date
    ON merchant_transaction (transaction_date);

CREATE INDEX idx_merchant_transaction_merchant_date
    ON merchant_transaction (merchant_id, transaction_date);
